Updated blerc config

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -2,8 +2,41 @@
 # ~/.bashrc
 #
 
-# Make sure the directory exists
-mkdir -p "${XDG_STATE_HOME}/bash"
+# ===============
+#    SETTINGS
+# ===============
+
+set -o emacs # set edit mode
+set -o pipefail # fail if any command in pipe fails
+shopt -s checkwinsize # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
+shopt -s extglob # enable extended pattern matching features, see http://wiki.bash-hackers.org/syntax/pattern
+shopt -s globstar 2>/dev/null # turn on recursive globbing (enables ** to recurse all directories)
+shopt -s autocd # a command name that is the name of a directory is executed as if it were the argument to the cd command.
+shopt -s direxpand # perform word expansion when trying filename completion useful when trying to type path with variable on it
+
+# minor errors in the spelling of a directory component in a cd command
+# will be corrected. The errors checked for are transposed characters,
+# a missing character, and one character too many. If a correction is found,
+# the corrected file name is printed, and the command proceeds.
+shopt -s cdspell 2>/dev/null
+
+# disable Ctrl-S ( flow control )
+stty -ixon
+
+# ===============
+# HISTORY CONTROL
+# ===============
+
+# don't save duplicates
+HISTCONTROL=ignoreboth:erasedups
+
+shopt -s histappend # append to the history file, don't overwrite it
+
+# set history length
+HISTSIZE=20000
+HISTFILESIZE=40000
+
+####################################################
 
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
@@ -36,6 +69,9 @@ export CARGO_INCREMENTAL=1
 
 [[ "$(whoami)" = "root" ]] && return
 
+# Make sure the directory exists
+mkdir -p "${XDG_STATE_HOME}/bash"
+
 # Python stuff is in there
 export PATH=~/.local/bin:$PATH
 
@@ -59,8 +95,6 @@ export QSYS_ROOTDIR="/home/kloud/QUARTUS/18.1/quartus/sopc_builder/bin"
 
 # Rootless docker
 export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
-
-export HISTCONTROL=ignoreboth
 
 gpgconf --launch gpg-agent
 export GPG_TTY=$(tty)
